const BAD_REQUEST_ERROR = 400;
const NOTFOUND_ERROR = 404;
const DEFAULT_ERROR = 500;
const FORBIDDEN_ERROR = 403;

module.exports = {
  BAD_REQUEST_ERROR,
  NOTFOUND_ERROR,
  DEFAULT_ERROR,
  FORBIDDEN_ERROR,
};
